# docker-compose.yml

services:
  local-da:
    # Reference: https://github.com/rollkit/local-da/pkgs/container/local-da
    image: ghcr.io/rollkit/local-da:cff7abd
    container_name: local-da
    ports:
      - "7980:7980"

  cyber:
    # Build the cyber image from the Dockerfile in the current directory
    # build: .
    # Or use the pre-built image from the GitHub Container Registry
    image: ghcr.io/cyborgshead/cyber-rollup:5954967
    container_name: cyber
    ports:
      # Map service ports to the host
      - "26657:26657" # RPC
      - "9090:9090"   # gRPC
      - "26656:26656" # P2P
      - "1317:1317"   # API
    volumes:
      # Mount your local host directory to the assumed data/config directory inside the container
      - ~/.cyber:/root/.cyber
    command: >
      cyber start
      --rollkit.aggregator
      --rollkit.da_address=http://local-da:7980
      --rpc.laddr=tcp://0.0.0.0:26657
      --grpc.address=0.0.0.0:9090
      --p2p.laddr=0.0.0.0:26656
      --api.address=tcp://0.0.0.0:1317
      --minimum-gas-prices='0.025stake'
      --home=/root/.cyber
    depends_on:
      # Ensure local-da and sequencer containers are started before cyber
      - local-da
